### ISSUE TITLE
Ensure Mentors can not make POST requests to EventMentors view when Event is not published

### ISSUE THREAD

**Issue by rosiemaguire** [SheCodesAus/layer_8_victory_backend_bris_2023#5]
- Add check on POST request to check published status of event. 
- If event.is_published=0, throw error.
- Might be able to rework something from pledge post request from crowdfunding project - https://github.com/rosiemaguire/Django-crowd-funding-project/blob/main/crowdfunding/projects/views.py#L82

**Comment by mayadomi** [comment]
Add this to the views.py for now :D

Plus a note on whether we should have mentor_id field conditional/input based on request.data['mentor_id'] field. eg, if supplied mentor_id <> request.user and request.user == is_staff, then set mentor_id = supplied mentor_id (ie its PO assigning mentors), otherwise set mentor_id to request.user (mentor self-assigning).... 

Hopefully that makes sense/I've understood the model/workflow correctly 😆

**Comment by mayadomi** [comment]
Doh! Just saw that the above note is issue #4 *facepalm*
